@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "FinanceBook Storage" #F4F6F6{
Class "<<interface>>\nFinanceBookStorage" as FinanceBookStorage
Class JsonFinanceBookStorage
Class JsonSerializableFinanceBook
Class JsonAdaptedExpense
Class JsonAdaptedCommission
Class "{abstract}\nJsonAdaptedFinance" as JsonAdaptedFinance
}

package "EventsBook Storage" #F4F6F6{
Class "<<interface>>\nEventsBookStorage" as EventsBookStorage
Class JsonEventsBookStorage
Class JsonSerializableEventsBook
Class JsonAdaptedEvent
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -down-> "1" AddressBookStorage
StorageManager -down-> "1" FinanceBookStorage
StorageManager -down-> "1" EventsBookStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> FinanceBookStorage
Storage -down-|> EventsBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonEventsBookStorage .up.|> EventsBookStorage
JsonEventsBookStorage ..> JsonSerializableEventsBook
JsonSerializableEventsBook --> "*" JsonAdaptedEvent
JsonAdaptedEvent --> "*" JsonAdaptedPerson

JsonFinanceBookStorage .up.|> FinanceBookStorage
JsonFinanceBookStorage ..> JsonSerializableFinanceBook
JsonSerializableFinanceBook --> "*" JsonAdaptedFinance
JsonAdaptedExpense -up-|> JsonAdaptedFinance
JsonAdaptedCommission -up-|> JsonAdaptedFinance

@enduml
